name: Pylint Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run pylint
      id: pylint
      run: |
        pylint --fail-under=0 --exit-zero $(find . -name "*.py" | grep -v "venv\|.git") | tee pylint_output.txt
        echo "PYLINT_SCORE=$(grep -oP '(?<=rated at )[0-9\.]+' pylint_output.txt || echo 0.0)" >> $GITHUB_ENV
    
    - name: Comment on results
      run: |
        echo "Pylint score: ${{ env.PYLINT_SCORE }}/10"
        if (( $(echo "${{ env.PYLINT_SCORE }} < 10" | bc -l) )); then
          echo "Warning: Pylint score is below 10.0"
        else
          echo "Great! Pylint score is 10.0"
        fi
