name: Pylint Check

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        id: pylint_check
        run: |
          SCORE=$(pylint script.py | grep "rated at" | awk '{print $(NF-1)}')
          if (( $(echo "$SCORE < 10" | bc -l) )); then
            echo "Pylint score is $SCORE/10. Failing pipeline!"
            exit 1
          else
            echo "Pylint score is 10/10. Passed!"
          fi

      - name: Fail job if pylint score is low
        if: failure()
        run: exit 1
